name: build-therian-feature-extractor
run-name: build-therian-feature-extractor
on: [push]
jobs:
  build-therian-feature-extractor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup nodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dev dependencies
        run: yarn install

      - name: Build Therian Feature Extractor
        run: yarn bundle

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: therian-feature-extractor
          path: therian-extractor.js
